version: "3.9"

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
    restart: always
  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: -source=file://migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable up
  scraper:
    build: posts_scraper/
    environment:
      - TZ=${TZ}
      - INSTAGRAM_LOGIN=${INSTAGRAM_LOGIN}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
    depends_on:
      - postgres
      - migrate
    restart: always